"use client";
import {useEffect,useRef,useState} from "react";
import {api,post} from "@/lib/api";
import type {User} from "@/lib/types";
import {ErrorMessage,Loading,VoiceButton} from "./ui";
type Unit={id:string;number:number;title:string;lesson_page:number;exercise_page:number;sections:{id:string;item_ids:string[]}[]};
type Progress={page?:number;answers?:Record<string,string>;exercise_correct?:number;exercise_total?:number;exercises_completed?:boolean;speaking_completed?:boolean;listening_completed?:boolean};
type Catalog={title:string;version:string;page_count:number;units:Unit[];progress:Record<string,Progress>;cursor?:{unit_id:string;page:number}};
type Question={id:string;kind:string;prompt:string;instruction_th:string;options:{id:string;text:string}[];example:boolean;answers?:string[]};
type Pack={explanation_th:string;pattern:string;questions:Question[];vocabulary:{term:string;meaning:string;example:string}[]};
type Detail={unit:Unit;version:string;status:string;pack?:Pack;progress:Progress};
type Mark={id:string;correct:boolean;reason_th:string;answer:string};
export default function LearnEbook({user,resume,review}:{user:User;resume:(id:string)=>void;review:()=>void}){
 const [book,setBook]=useState<Catalog>(),[detail,setDetail]=useState<Detail>(),[selected,setSelected]=useState(""),[page,setPage]=useState(1),[search,setSearch]=useState("");
 const [answers,setAnswers]=useState<Record<string,string>>({}),[section,setSection]=useState(""),[marks,setMarks]=useState<Record<string,Mark>>({}),[reveals,setReveals]=useState<Record<string,{answers:string[];explanation_th:string}>>({});
 const [error,setError]=useState(""),[busy,setBusy]=useState(false),[saved,setSaved]=useState("");
 const draft=useRef({id:"",version:"",page:1,answers:{} as Record<string,string>}),checking=useRef("");
 const saves=useRef(Promise.resolve());
 const storage=(id:string,version:string)=>`toko-ebook:${user.id}:${version}:${id}`;
 async function save(){const d={...draft.current};if(!d.id)return;const cached=JSON.stringify({answers:d.answers});const task=saves.current.catch(()=>{}).then(async()=>{await api(`/ebook/units/${d.id}/progress`,{method:"PATCH",body:JSON.stringify({page:d.page,answers:d.answers})});const key=storage(d.id,d.version);if(localStorage.getItem(key)===cached)localStorage.removeItem(key);setSaved("บันทึกแล้ว")});saves.current=task;await task}

 async function open(id:string,initialPage?:number){setBusy(true);setError("");try{await save();const d=await api<Detail>(`/ebook/units/${id}`);let a=d.progress.answers||{};try{const local=JSON.parse(localStorage.getItem(storage(id,d.version))||"null");if(local)a=local.answers||a}catch{}const n=initialPage||d.progress.page||d.unit.lesson_page;draft.current={id,version:d.version,page:n,answers:a};setDetail(d);setSelected(id);setPage(n);setAnswers(a);setSection(d.unit.sections[0]?.id||"");setMarks({});setReveals({});checking.current="";await save()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{void api<Catalog>("/ebook").then(b=>{setBook(b);if(b.cursor)void open(b.cursor.unit_id,b.cursor.page)}).catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(detail?.status!=="queued")return;const timer=setInterval(()=>{void api<Detail>(`/ebook/units/${detail.unit.id}`).then(d=>setDetail(d)).catch(e=>setError(e.message))},2500);return()=>clearInterval(timer)},[detail?.status,detail?.unit.id]);
 useEffect(()=>{if(!selected)return;const timer=setTimeout(()=>{void save().catch(e=>{setSaved("ร่างเก็บในเครื่องแล้ว ยังส่งเข้าเซิร์ฟเวอร์ไม่ได้");setError(e.message)})},700);return()=>clearTimeout(timer)},[answers,page,selected]);
 function changePage(n:number){if(!book)return;n=Math.max(1,Math.min(book.page_count,n));setPage(n);draft.current.page=n;setSaved("กำลังบันทึก…")}
 function answer(id:string,value:string){const a={...answers,[id]:value};setAnswers(a);draft.current.answers=a;localStorage.setItem(storage(selected,draft.current.version),JSON.stringify({answers:a}));setMarks(m=>{const copy={...m};delete copy[id];return copy});checking.current="";setSaved("กำลังบันทึก…")}
 async function prepare(){setBusy(true);setError("");try{const r=await post<{status:string}>(`/ebook/units/${selected}/prepare`,{});setDetail(d=>d?{...d,status:r.status}:d);if(r.status==="ready")setDetail(await api<Detail>(`/ebook/units/${selected}`))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const questions=detail?.pack?.questions.filter(q=>q.id.startsWith(section+":"))||[];
 async function check(){setBusy(true);setError("");try{await save();checking.current ||= crypto.randomUUID();const chosen=Object.fromEntries(questions.filter(q=>!q.example).map(q=>[q.id,answers[q.id]||""]));const r=await post<{marks:Mark[];progress:Progress}>(`/ebook/units/${selected}/check`,{request_id:checking.current,answers:chosen});setMarks(m=>({...m,...Object.fromEntries(r.marks.map(v=>[v.id,v]))}));setDetail(d=>d?{...d,progress:r.progress}:d);checking.current=""}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function reveal(id:string){setBusy(true);try{const r=await post<Record<string,{answers:string[];explanation_th:string}>>(`/ebook/units/${selected}/reveal`,{ids:[id]});setReveals(v=>({...v,...r}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function oral(mode:string){setBusy(true);setError("");try{await save();const r=await post<{id:string}>(`/ebook/units/${selected}/sessions`,{mode,request_id:crypto.randomUUID()});resume(r.id)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <><div className="page-intro"><span className="eyebrow">READ · TRY · LISTEN · SPEAK</span><h1>Learn Ebook</h1><p>หนังสือต้นฉบับทุกหน้า · ทำโจทย์เดิม แล้วนำไปฟังและพูดในชีวิตจริง</p></div><ErrorMessage message={error}/>{!book?<Loading/>:<>
 <div className="button-row"><button className="button" onClick={review}>ทบทวนข้อที่เคยผิด</button><span>{book.units.length} บท · {book.page_count} หน้า</span></div>
 <div className="ebook-layout"><aside className="card ebook-index"><label>ค้นหาบท<input aria-label="ค้นหาบท Ebook" value={search} onChange={e=>setSearch(e.target.value)} placeholder="เช่น present, past, 12"/></label><div className="ebook-units">{book.units.filter(u=>(u.number+" "+u.title).toLowerCase().includes(search.toLowerCase())).map(u=>{const p=u.id===selected?detail?.progress:book.progress[u.id];return <button key={u.id} className={`ebook-unit ${u.id===selected?"active":""}`} disabled={busy} onClick={()=>void open(u.id)}><strong>{u.number}. {u.title}</strong><small>{p?.exercises_completed?"✓ แบบฝึก ":p?.exercise_correct?`แบบฝึก ${p.exercise_correct}/${p.exercise_total} `:""}{p?.listening_completed?"✓ ฟัง ":""}{p?.speaking_completed?"✓ พูด":p?.page?" · เคยเปิดเรียน":""}</small></button>})}</div></aside>
 <section className="ebook-body">{!detail?<div className="card ebook-panel"><h2>เลือกบทที่อยากเรียน</h2><p>อ่านหน้าต้นฉบับ ทำโจทย์ ฝึกฟังและพูด แล้วกลับมาทบทวนได้ทุกเมื่อ</p></div>:<>
 <div className="card ebook-panel"><h2>Unit {detail.unit.number} · {detail.unit.title}</h2><div className="button-row"><button className="button" onClick={()=>changePage(detail.unit.lesson_page)}>เนื้อหาต้นฉบับ</button><button className="button" onClick={()=>changePage(detail.unit.exercise_page)}>โจทย์ต้นฉบับ</button><span role="status">{saved}</span></div><div className="ebook-page-nav"><button className="button" disabled={page<=1} onClick={()=>changePage(page-1)}>หน้าก่อน</button><label>หน้า PDF <input type="number" aria-label="หน้า PDF" min={1} max={book.page_count} value={page} onChange={e=>changePage(Number(e.target.value)||1)}/></label><span>/ {book.page_count}</span><button className="button" disabled={page>=book.page_count} onClick={()=>changePage(page+1)}>หน้าถัดไป</button></div><a href={`/api/ebook/pages/${page}`} target="_blank" rel="noreferrer" title="เปิดภาพขนาดเต็ม"><img className="ebook-page" src={`/api/ebook/pages/${page}`} alt={`หนังสือต้นฉบับ หน้า ${page}`} loading="lazy"/></a><small>แตะภาพเพื่อขยาย · อ่านสารบัญ ภาคผนวกและเฉลยท้ายเล่มได้ผ่านเลขหน้า</small></div>
 {!detail.pack?<div className="card ebook-panel"><h3>แบบฝึกโต้ตอบตามโจทย์เดิม</h3><p>เตรียมครั้งแรกด้วย AI แล้วเก็บไว้ใช้ซ้ำทุกครั้ง อาจใช้เวลา 1–2 นาทีและนับในงบของผู้เริ่มเตรียม</p>{detail.status==="queued"?<p role="status">กำลังเตรียมโจทย์ คำอธิบาย และแบบฝึกฟัง–พูด… อ่านต้นฉบับรอได้ หรือกลับมาเปิดต่อภายหลัง</p>:<button className="button primary" disabled={busy} onClick={()=>void prepare()}>{detail.status==="failed"?"เตรียมแบบฝึกอีกครั้ง":"เตรียมแบบฝึกบทนี้"}</button>}</div>:<>
 <div className="card ebook-panel"><h3>เข้าใจแล้วลองใช้</h3><p className="preserve-lines">{detail.pack.explanation_th}</p><strong>{detail.pack.pattern}</strong><h3>คำศัพท์ในบท</h3>{detail.pack.vocabulary.map(w=><div className="ebook-word" key={w.term}><strong>{w.term}</strong> — {w.meaning}<p>{w.example}</p><VoiceButton text={w.example} voice={user.profile.voice} speed={user.profile.speed}/><button className="text-button" disabled={busy} onClick={()=>{setBusy(true);void post("/vocabulary",{term:w.term,meaning:w.meaning,example:w.example}).then(()=>setSaved("เก็บคำศัพท์แล้ว")).catch(e=>setError(e.message)).finally(()=>setBusy(false))}}>เก็บคำศัพท์</button></div>)}</div>
 <div className="card ebook-panel"><h3>ทำโจทย์ต้นฉบับ</h3><p>ตอบคำในช่องว่างตามโจทย์ ถ้ามีหลายช่องให้เขียนเรียงกัน · คำตอบที่ถูกตามบริบทยืดหยุ่นได้</p><div className="button-row">{detail.unit.sections.map(s=><button className={`button ${section===s.id?"primary":""}`} key={s.id} disabled={busy} onClick={()=>{setSection(s.id);checking.current=""}}>{s.id}</button>)}</div>
 {questions.map(q=><div className="ebook-question" key={q.id}><label htmlFor={`q-${q.id}`}><strong>{q.id.replace(":"," · ")}</strong><p className="preserve-lines">{q.prompt}</p><small>{q.instruction_th}</small></label>{q.example?<p className="notice">ตัวอย่างในหนังสือ: {q.answers?.join(" / ")}</p>:q.kind==="write"?<textarea id={`q-${q.id}`} aria-label={`คำตอบ ${q.id}`} rows={2} disabled={busy} maxLength={2000} value={answers[q.id]||""} onChange={e=>answer(q.id,e.target.value)}/>:<select disabled={busy} id={`q-${q.id}`} aria-label={`คำตอบ ${q.id}`} value={answers[q.id]||""} onChange={e=>answer(q.id,e.target.value)}><option value="">เลือกคำตอบ / จับคู่</option>{q.options.map(o=><option value={o.id} key={o.id}>{o.id}. {o.text}</option>)}</select>}{marks[q.id]&&<div role="status" className="notice">{marks[q.id].correct?"✓ ถูกต้อง":"ลองปรับอีกนิด"} · {marks[q.id].reason_th}{!marks[q.id].correct&&<p>{marks[q.id].answer}</p>}</div>}{!q.example&&<button className="text-button" disabled={busy} onClick={()=>void reveal(q.id)}>ขอดูเฉลยข้อนี้</button>}{reveals[q.id]&&<p className="notice">{reveals[q.id].answers.join(" / ")} — {reveals[q.id].explanation_th}</p>}</div>)}
 <button className="button primary" disabled={busy||!questions.some(q=>!q.example)||questions.some(q=>!q.example&&!answers[q.id]?.trim())} onClick={()=>void check()}>{busy?"กำลังตรวจ…":"ตรวจคำตอบชุดนี้"}</button><p>ทำถูกแล้ว {detail.progress.exercise_correct||0}/{detail.progress.exercise_total||detail.pack.questions.filter(q=>!q.example).length} ข้อ · ข้อที่ผิดจะเข้าแผนทบทวน</p></div>
 <div className="card ebook-panel"><h3>ท้ายบท: ฟังให้เข้าใจ พูดให้ใช้ได้</h3><p>แต่ละทักษะใช้ 2 รอบที่ทำได้ด้วยตัวเอง พูดต้องมีเสียงจริง ส่วนการฟังตอบตามความหมายได้ ไม่ต้องท่องประโยค</p><div className="button-row"><button className="button primary" disabled={busy} onClick={()=>void oral("listening")}>ฝึกฟังท้ายบท {detail.progress.listening_completed?"✓":""}</button><button className="button charcoal" disabled={busy} onClick={()=>void oral("speak")}>ฝึกพูดท้ายบท {detail.progress.speaking_completed?"✓":""}</button></div></div>
 </>}
 </>}</section></div></>}
 </>;
}
